apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJaR2xoYm5semIyWXhNQzB3TTBCb2IzUnRZV2xzTG1OdmJUcGtiM0JmZGpGZk9HVTFOV1E0WkdVM05UWTJOelF5WldNMlltSXhZbVEyTVRjeVpqZ3hNMlF4TjJJMFlXTmlNRGszWVdaa04ySXlNakkzTnpJd09XUTBZVGxqWlRWaE5RPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-network-health-registry
  namespace: network-dashboard
type: kubernetes.io/dockerconfigjson
